<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SinemaBiletSistemi.DataAccess\SinemaBiletSistemi.DataAccess.csproj" />
    <ProjectReference Include="..\SinemaBiletSistemi.Entities\SinemaBiletSistemi.Entities.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
